services:
  - type: worker
    name: paleotti-bot
    env: python
    region: frankfurt
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
