services:
  - type: worker
    name: paleotti-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    autoDeploy: true
